name: Continuous delivery

on:
  release:
    types: published

  workflow_dispatch:

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: alvidir/rauth

jobs:
  publish-to-crates-dot-io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
